// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkizDdgQzj_KkYefmwIJFyekGzT-B1a0s',
    appId: '1:1002561958577:android:cdc65d03cae1e99b7fe890',
    messagingSenderId: '1002561958577',
    projectId: 'ibnt-3bcff',
    storageBucket: 'ibnt-3bcff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09c0JebUuowPT51z06apgfEQGanNQAM8',
    appId: '1:1002561958577:ios:1f7aba536a1702197fe890',
    messagingSenderId: '1002561958577',
    projectId: 'ibnt-3bcff',
    storageBucket: 'ibnt-3bcff.appspot.com',
    androidClientId: '1002561958577-d78m297tc2lpcons9icp7hoqne6kvb07.apps.googleusercontent.com',
    iosClientId: '1002561958577-u1im0pfiidgmphnou77v4tics0j2jc67.apps.googleusercontent.com',
    iosBundleId: 'br.com.jr.appIbnt',
  );
}
